"""LGPD catalog generated from the layouts: documentation and Unity Catalog tags."""

from __future__ import annotations

from housing_lakehouse.layouts import DROP, KEEP, LAYOUTS, PSEUDONYMIZE, SENSITIVE, Layout


def published_columns(layout: Layout) -> list[tuple[str, str, str]]:
    """(silver column, category, action) for everything that survives the policy."""
    out = []
    for col in layout.columns:
        if col.action == DROP:
            continue
        out.append((col.target_name, col.category, col.action))
        if col.action == PSEUDONYMIZE and col.document:
            out.append((f"{col.document}_status", "personal", KEEP))
    return out


def unity_catalog_tag_sql(table: str, layout: Layout) -> list[str]:
    """Statements that tag the silver table columns in Unity Catalog (basis for masks and ABAC)."""
    return [
        f"ALTER TABLE {table} ALTER COLUMN `{name}` "
        f"SET TAGS ('lgpd_category' = '{category}', 'lgpd_treatment' = '{action}')"
        for name, category, action in published_columns(layout)
    ]


def render_markdown(layouts: dict[str, Layout] | None = None) -> str:
    layouts = layouts or LAYOUTS
    lines = [
        "# LGPD catalog of the sources",
        "",
        "Generated by `housing catalog` from `src/housing_lakehouse/layouts.py`. Do not edit by hand.",
        "",
        "| Action | Effect in silver |",
        "|---|---|",
        "| keep | column carries on with the same content |",
        "| drop | column never leaves bronze |",
        "| pseudonymize | keyed HMAC-SHA256: joinable across datasets, irreversible without the key |",
        "| generalize | loses precision (ZIP code → 5 digits, birth date → age) |",
        "",
    ]
    for layout in layouts.values():
        dropped = sum(c.action == DROP for c in layout.columns)
        sensitive = [c.name for c in layout.columns if c.category == SENSITIVE and c.action != DROP]
        lines += [
            f"## {layout.name}",
            "",
            f"{len(layout.columns)} source columns; {dropped} dropped; "
            f"{len(sensitive)} sensitive kept{': ' + ', '.join(sensitive) if sensitive else ''}.",
            "",
            "| Source column | Type | Category | Action | Silver column | Note |",
            "|---|---|---|---|---|---|",
        ]
        for c in layout.columns:
            target = "" if c.action == DROP else f"`{c.target_name}`"
            lines.append(f"| `{c.name}` | {c.dtype} | {c.category} | {c.action} | {target} | {c.note} |")
        lines.append("")
    return "\n".join(lines)
